package Modelo;
// Generated 18/08/2016 22:20:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Magnifyingglass generated by hbm2java
 */
public class Magnifyingglass  implements java.io.Serializable {


     private Long id;
     private String name;
     private int quantity;
     private Set<User> users = new HashSet<User>(0);

    public Magnifyingglass() {
    }

	
    public Magnifyingglass(String name, int quantity) {
        this.name = name;
        this.quantity = quantity;
    }
    public Magnifyingglass(String name, int quantity, Set<User> users) {
       this.name = name;
       this.quantity = quantity;
       this.users = users;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


