package Modelo;
// Generated 07/09/2016 11:45:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Long id;
     private String name;
     private Date dateC;
     private Date dateD;
     private Set<User> users = new HashSet<User>(0);

    public Profile() {
    }

	
    public Profile(String name, Date dateC) {
        this.name = name;
        this.dateC = dateC;
    }
    public Profile(String name, Date dateC, Date dateD, Set<User> users) {
       this.name = name;
       this.dateC = dateC;
       this.dateD = dateD;
       this.users = users;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateC() {
        return this.dateC;
    }
    
    public void setDateC(Date dateC) {
        this.dateC = dateC;
    }
    public Date getDateD() {
        return this.dateD;
    }
    
    public void setDateD(Date dateD) {
        this.dateD = dateD;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


