package Modelo;
// Generated 18/08/2016 22:20:12 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private Magnifyingglass magnifyingglass;
     private String image;
     private String name;
     private String lastName;
     private int level;
     private String presentation;
     private int telephone;
     private String type;
     private String email;
     private String userName;
     private String password;
     private String state;

    public User() {
    }

    public User(Magnifyingglass magnifyingglass, String image, String name, String lastName, int level, String presentation, int telephone, String type, String email, String userName, String password, String state) {
       this.magnifyingglass = magnifyingglass;
       this.image = image;
       this.name = name;
       this.lastName = lastName;
       this.level = level;
       this.presentation = presentation;
       this.telephone = telephone;
       this.type = type;
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.state = state;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Magnifyingglass getMagnifyingglass() {
        return this.magnifyingglass;
    }
    
    public void setMagnifyingglass(Magnifyingglass magnifyingglass) {
        this.magnifyingglass = magnifyingglass;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public String getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }
    public int getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


