package Modelo;
// Generated 07/09/2016 11:45:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private Magnifyingglass magnifyingglass;
     private Profile profile;
     private String image;
     private String name;
     private String lastName;
     private Integer level;
     private String presentation;
     private Integer telephone;
     private String type;
     private String email;
     private String userName;
     private String password;
     private String state;
     private Date dateC;
     private Date dateD;

    public User() {
    }

	
    public User(Profile profile, String name, String lastName, String userName, String password, Date dateC, Date dateD) {
        this.profile = profile;
        this.name = name;
        this.lastName = lastName;
        this.userName = userName;
        this.password = password;
        this.dateC = dateC;
        this.dateD = dateD;
    }
    public User(Magnifyingglass magnifyingglass, Profile profile, String image, String name, String lastName, Integer level, String presentation, Integer telephone, String type, String email, String userName, String password, String state, Date dateC, Date dateD) {
       this.magnifyingglass = magnifyingglass;
       this.profile = profile;
       this.image = image;
       this.name = name;
       this.lastName = lastName;
       this.level = level;
       this.presentation = presentation;
       this.telephone = telephone;
       this.type = type;
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.state = state;
       this.dateC = dateC;
       this.dateD = dateD;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Magnifyingglass getMagnifyingglass() {
        return this.magnifyingglass;
    }
    
    public void setMagnifyingglass(Magnifyingglass magnifyingglass) {
        this.magnifyingglass = magnifyingglass;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
    public String getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }
    public Integer getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Date getDateC() {
        return this.dateC;
    }
    
    public void setDateC(Date dateC) {
        this.dateC = dateC;
    }
    public Date getDateD() {
        return this.dateD;
    }
    
    public void setDateD(Date dateD) {
        this.dateD = dateD;
    }




}


